service: fitbit

provider:
  name: aws
  runtime: python3.6
  profile: myaws
  region: ap-northeast-1
#  environment:
#    AWS_PROFILE: myaws


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*" 
      Resource:
        Fn::Join:
          - ""
          - - "*"

package:
  include:
    - vendored/**
    - mymodule/**
    - handler.py
  exclude:
    - requirements.txt
    - serverless.yml

functions:
  fitbit:
    handler: handler.handler

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: fitbit_test 
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
